### ISSUE TITLE
Are there collisions for MurmurHash3_x86_32 with a 4 byte key?

### ISSUE THREAD

**Issue by mrjbom** [aappleby/smhasher#104]
I have seen mention that for MurmurHash in the case of a 4 byte key, there are no collisions, it is true?
It possible to write a hash table using `MurmurHash3_x86_32(&key, 4, 0, &hash)` hash function for a key of type uint32_t without worrying about collisions and collision resolution?
Just calculating the position in the hash map like this: `pos = hash % current_hash_table_size`?

**Comment by sebres** [comment]
> I have seen mention that for MurmurHash in the case of a 4 byte key, there are no collisions, it is true?

No, it is false. It cannot be excluded by algorithm because of `h1 *= 5` in this line:
https://github.com/aappleby/smhasher/blob/61a0530f28277f2e850bfc39600ce61d02b518de/src/MurmurHash3.cpp#L120
simply because it could loss few significant bits for h1 values at that point that are larger than `0xFFFFFFFF/5 == 0x33333333`.

It is simple to test, basically a collision can be found already for 
`0x33333a38` (`858995256`) |Ꭓ| `0x87f30` (`556848`) → `10c5a678` (`281388664`):
```tcl
# mm3-x86-32 as hex for 2 values:
% hash -mm3-32 -hex -binary [hex_decode 87f30]
10c5a678
% hash -mm3-32 -hex -binary [hex_decode 33333a38]
10c5a678

# same as decimal (integer):
% hash -mm3-32 -dec -binary [bin_decode -dec 556848]
281388664
% hash -mm3-32 -dec -binary [bin_decode -dec 858995256]
281388664
```
Note `0x33333333` is not the initial value, but intermediate h1-value at time point of MUL operation.
Also other numbers are imaginable... Here is another example for a collision:
`0x10c5b3d1` (`281392081`) |Ꭓ| `0x332c8` (`209608`) → `ceb411d3` (`3467907539`)

And so forth...
It is pretty obvious if one can read source code and understand math.

> It possible to write a hash table using `MurmurHash3_x86_32(&key, 4, 0, &hash)` hash function for a key of type uint32_t without worrying about collisions and collision resolution?

The answer is clearly and surely - no.

But why? I mean why someone want to hash 4 bytes with no matter which algorithm to get 4 bytes back?
This would only cost time and computing power for nothing.
I mean without to consider some hardening or cryptographic reason (note that MM3 is not cryptographically strong hashing algorithm).

**Comment by mrjbom** [comment]
> It is simple to test, basically a collision can be found already for `0x33333a38` (`858995256`) |Ꭓ| `0x87f30` (`556848`) → `10c5a678` (`281388664`):
> 
> ```tcl
> # mm3-x86-32 as hex for 2 values:
> % hash -mm3-32 -hex -binary [hex_decode 87f30]
> 10c5a678
> % hash -mm3-32 -hex -binary [hex_decode 33333a38]
> 10c5a678
@aappleby, How did you calculate these hashes? I get different and distinct hashes for these keys.
Moreover, I ran all keys from 0 to 0xFFFFFFFF and never got a repeated hash.
I used MurmurHash3_x86_32(&key, sizeof(uint32_t), 0, &hash);

**Comment by sebres** [comment]
> @aappleby, How did you calculate these hashes?

Take a closer look at the answer account name attentively - the answer was not from aappleby.

Sorry, my bad...
The `[hex_decode 87f30]` (and `[bin_decode -dec 556848]`) produce a binary `\0x08\0x7f\0x30` (3 bytes long).
It doesn't have padding to integer, so collides because of variable length with `\0x33\0x33\0x3a\0x38` (4 bytys long), 
due to 0x101010101 values == (0x1_0000_0000 (4 bytes long) + 0x100_0000 (3 bytes long) + ... 1 (0 bytes long)),
but also because of this operation:
https://github.com/aappleby/smhasher/blob/61a0530f28277f2e850bfc39600ce61d02b518de/src/MurmurHash3.cpp#L141

The line (with MUL) I provided above as hint for a possible collision:
https://github.com/aappleby/smhasher/blob/61a0530f28277f2e850bfc39600ce61d02b518de/src/MurmurHash3.cpp#L120
doesn't matter for exact 4 bytes, because `h1` is only one part, another is `k1` which remain unique by 1 block with same length, since over `k1` (and finaly hash value) it only uses ROTL32/XOR operations which are safe against bit-loss.
So no significant bits get lost here by exactly 4 bytes input.

This means: 
- For **fixed exactly** 4 bytes long input, there is indeed no collisions.
- For **variable length** 0..4 bytes long input, there are clearly 0x1010101 collisions.

> Moreover, I ran all keys from 0 to 0xFFFFFFFF and never got a repeated hash.

Agree... but, again, for the ints (fixed 4 bytes) only. 
<details><summary>Here is also small PoC (if someone need it, e. g. to test another hash)...</summary>

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "MurmurHash3.cpp"

// LONG_POC - if 1 slow variant with verbose output (expects 16.5GB memory usage, so 64-bits only), 
//            otherwise fast (slots only) version   (expects  0.5GB memory only)
#ifndef LONG_POC
#  define LONG_POC 0
#endif

int main()
{
  unsigned int i, o, p, m, collCnt = 0;
  unsigned char *used;
#if LONG_POC
  unsigned int *harr;
#endif
  unsigned long long cnt = 0;

  // ca. 537MB with slots each 8 used hashes (to detect a hash is already used):
  used = malloc(0x100000000L/8 * sizeof(*used)); // (each bit hold used flag, 1 - used, 0 - otherwise)
  memset(used, 0, 0x100000000L/8 * sizeof(*used));
#if LONG_POC
  // 16GB containing 4G * 4 bytes hashes (to get an original value from hash):
  harr = malloc(0x100000000L * sizeof(o));
  memset(harr, 0, 0x100000000L * sizeof(o));
#endif
  
  for (i = 0 ; ; i++) {
    cnt++;
    MurmurHash3_x86_32 ( &i, sizeof(i), 0, &o );
    p = o / 8; m = 1 << (o % 8);
    //printf("0x%08x -> 0x%08x .. [0x%08x] & 0x%02x == %u\n", i, o, p, m, (used[p] & m) ? 1 : 0);
    if ((cnt % 0x100000) == 0) { // progress
      printf("."); fflush(stdout); 
      if ((cnt % (64*0x100000)) == 0) { // full line
        printf(" %2u / %2u\n", (unsigned)(cnt/(64*0x100000)), (unsigned)(0x100000000L / (64*0x100000))); fflush(stdout);
      }
    }
    if (used[p] & m) {
#if LONG_POC
      printf("\ncollision: %u (%X) with %u (%X) on same hash %u (%X)\n", i,i, harr[o],harr[o], o,o);
#else
      printf("\ncollision: %u (%X) on same hash %u (%X)\n", i,i, o,o);
#endif
      collCnt++;
      goto next;
    }
    used[p] |= m; // mark as used
#if LONG_POC
    harr[o] = i;  // save previous input for this hash
#endif
next:
    if (i == 0xFFFFFFFF) break;
  } 
  printf("\n%u collision(s) found for %llu integers.\n", collCnt, cnt);
  
  // small algo check:
  if (!collCnt) {
    for (p = 0; p < 0x100000000L/8; p++) {
      if (used[p] != 0xFF) { // not all bits set
        printf("wrong slot %u - %X != FF\n", p, (unsigned)used[p]);
        exit(1);
      }
    }
    printf("check passed (all slots filled).\n");
  }
  return 0;
}
```
</details>

Sorry for confusion... (I edited my comment above with a warning for variable length)

**Comment by mrjbom** [comment]
@sebres, Everything is clear to me now. Thank you for the excellent answer!
